services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - auth_mock
      - remote_redis

  auth_mock:
    build:
      context: .
    command: python auth_mock/server.py
    env_file:
      - .env.dev
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    networks:
      - default

  remote_redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
    networks:
      - default

networks:
  shared_backend:
    external: true
    name: ${SHARED_DB_NETWORK:-pg-carthographie_backend}
