from __future__ import annotations

import os
from pathlib import Path

from django.conf import settings
import psycopg
import pytest
from psycopg import sql


def _env(name: str, default: str) -> str:
    return str(os.environ.get(name, default)).strip()


def _ensure_template_database() -> None:
    db_host = _env("DB_HOST", "127.0.0.1")
    db_port = int(_env("DB_PORT", "5432"))
    db_user = _env("DB_USER", "carthographie")
    db_password = _env("DB_PASSWORD", "carthographie")
    db_template = _env("DB_TEST_TEMPLATE", "lss_local_template")

    with psycopg.connect(
        host=db_host,
        port=db_port,
        dbname="postgres",
        user=db_user,
        password=db_password,
        autocommit=True,
    ) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM pg_database WHERE datname = %s",
                (db_template,),
            )
            if cursor.fetchone() is None:
                cursor.execute(
                    sql.SQL("CREATE DATABASE {} OWNER {}").format(
                        sql.Identifier(db_template),
                        sql.Identifier(db_user),
                    )
                )

    with psycopg.connect(
        host=db_host,
        port=db_port,
        dbname=db_template,
        user=db_user,
        password=db_password,
        autocommit=True,
    ) as template_connection:
        with template_connection.cursor() as cursor:
            cursor.execute("CREATE SCHEMA IF NOT EXISTS lss")
            cursor.execute("CREATE SCHEMA IF NOT EXISTS users")
            cursor.execute("CREATE SCHEMA IF NOT EXISTS common")
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS users.users (
                    id uuid PRIMARY KEY,
                    username varchar(255),
                    first_name varchar(255),
                    last_name varchar(255),
                    email varchar(255),
                    enabled boolean DEFAULT TRUE,
                    email_verified boolean DEFAULT FALSE,
                    synced_at time,
                    last_login_at time
                )
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS common.genres (
                    genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "group" varchar(255),
                    name varchar(255)
                )
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS common.artists (
                    artist_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name varchar(255)
                )
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS common.bands (
                    band_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name varchar(255)
                )
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS common.targets (
                    target_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name varchar(255) UNIQUE,
                    sort_order integer NOT NULL
                )
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS common.g_groups (
                    group_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name varchar(255) NOT NULL,
                    info text NULL,
                    secret_ciphertext text NULL,
                    status varchar(32) NOT NULL DEFAULT 'open',
                    CONSTRAINT g_groups_status_check
                        CHECK (status IN ('open', 'private'))
                )
                """
            )
            cursor.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS g_groups_name_unique
                    ON common.g_groups (lower(name))
                """
            )
            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS g_groups_status_idx
                    ON common.g_groups (status)
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS common.g_group_user (
                    group_id integer NOT NULL,
                    member_id uuid NOT NULL,
                    is_group_admin boolean NOT NULL DEFAULT false,
                    am_access boolean NOT NULL DEFAULT false,
                    PRIMARY KEY (group_id, member_id)
                )
                """
            )
            cursor.execute(
                """
                ALTER TABLE common.g_group_user
                    ADD COLUMN IF NOT EXISTS am_access boolean NOT NULL DEFAULT false
                """
            )
            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS g_group_user_is_group_admin_idx
                    ON common.g_group_user (is_group_admin)
                """
            )
            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS g_group_user_am_access_idx
                    ON common.g_group_user (am_access)
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS common.g_group_user_ask_to_join (
                    group_id integer NOT NULL,
                    member_id uuid NOT NULL,
                    PRIMARY KEY (group_id, member_id)
                )
                """
            )
            cursor.execute(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'g_group_user_group_fk'
                          AND conrelid = 'common.g_group_user'::regclass
                    ) THEN
                        ALTER TABLE common.g_group_user
                            ADD CONSTRAINT g_group_user_group_fk
                            FOREIGN KEY (group_id)
                            REFERENCES common.g_groups (group_id)
                            ON DELETE CASCADE;
                    END IF;
                END;
                $$;
                """
            )
            cursor.execute(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'g_group_user_member_fk'
                          AND conrelid = 'common.g_group_user'::regclass
                    ) THEN
                        ALTER TABLE common.g_group_user
                            ADD CONSTRAINT g_group_user_member_fk
                            FOREIGN KEY (member_id)
                            REFERENCES users.users (id)
                            ON DELETE CASCADE;
                    END IF;
                END;
                $$;
                """
            )
            cursor.execute(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'g_group_user_ask_to_join_group_fk'
                          AND conrelid = 'common.g_group_user_ask_to_join'::regclass
                    ) THEN
                        ALTER TABLE common.g_group_user_ask_to_join
                            ADD CONSTRAINT g_group_user_ask_to_join_group_fk
                            FOREIGN KEY (group_id)
                            REFERENCES common.g_groups (group_id)
                            ON DELETE CASCADE;
                    END IF;
                END;
                $$;
                """
            )
            cursor.execute(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'g_group_user_ask_to_join_member_fk'
                          AND conrelid = 'common.g_group_user_ask_to_join'::regclass
                    ) THEN
                        ALTER TABLE common.g_group_user_ask_to_join
                            ADD CONSTRAINT g_group_user_ask_to_join_member_fk
                            FOREIGN KEY (member_id)
                            REFERENCES users.users (id)
                            ON DELETE CASCADE;
                    END IF;
                END;
                $$;
                """
            )


@pytest.fixture(scope="session", autouse=True)
def prepare_postgres_test_template() -> None:
    _ensure_template_database()


@pytest.fixture(scope="session", autouse=True)
def prepare_static_root() -> None:
    Path(settings.STATIC_ROOT).mkdir(parents=True, exist_ok=True)
