from __future__ import annotations

import os

import psycopg
import pytest
from psycopg import sql


def _env(name: str, default: str) -> str:
    return str(os.environ.get(name, default)).strip()


def _ensure_template_database() -> None:
    db_host = _env("DB_HOST", "127.0.0.1")
    db_port = int(_env("DB_PORT", "5432"))
    db_user = _env("DB_USER", "carthographie")
    db_password = _env("DB_PASSWORD", "carthographie")
    db_template = _env("DB_TEST_TEMPLATE", "lss_local_template")

    with psycopg.connect(
        host=db_host,
        port=db_port,
        dbname="postgres",
        user=db_user,
        password=db_password,
        autocommit=True,
    ) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM pg_database WHERE datname = %s",
                (db_template,),
            )
            if cursor.fetchone() is None:
                cursor.execute(
                    sql.SQL("CREATE DATABASE {} OWNER {}").format(
                        sql.Identifier(db_template),
                        sql.Identifier(db_user),
                    )
                )

    with psycopg.connect(
        host=db_host,
        port=db_port,
        dbname=db_template,
        user=db_user,
        password=db_password,
        autocommit=True,
    ) as template_connection:
        with template_connection.cursor() as cursor:
            cursor.execute("CREATE SCHEMA IF NOT EXISTS lss")
            cursor.execute("CREATE SCHEMA IF NOT EXISTS users")
            cursor.execute("CREATE SCHEMA IF NOT EXISTS common")
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS users.users (
                    id uuid PRIMARY KEY,
                    username varchar(255),
                    first_name varchar(255),
                    last_name varchar(255),
                    email varchar(255),
                    enabled boolean DEFAULT TRUE,
                    email_verified boolean DEFAULT FALSE,
                    synced_at time,
                    last_login_at time
                )
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS common.genres (
                    genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "group" varchar(255),
                    name varchar(255)
                )
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS common.artists (
                    artist_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name varchar(255)
                )
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS common.bands (
                    band_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name varchar(255)
                )
                """
            )


@pytest.fixture(scope="session", autouse=True)
def prepare_postgres_test_template() -> None:
    _ensure_template_database()
