services:
  web:
    image: carthographie/lyrics-slide-show:latest
    command: >
      sh -c "scripts/wait_for_db.sh &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn lyrics_slide_show.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/static:ro
      - /etc/letsencrypt/live/www.carthographie.fr:/etc/letsencrypt/live/www.carthographie.fr:ro
      - /etc/letsencrypt/archive/www.carthographie.fr:/etc/letsencrypt/archive/www.carthographie.fr:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: {}