[pytest]
DJANGO_SETTINGS_MODULE = lyrics_slide_show.settings
python_files = tests.py test_*.py *_tests.py
env =
    D:DB_HOST=127.0.0.1
    D:DB_PORT=5432
    D:DB_NAME=carthographie
    D:DB_USER=carthographie
    D:DB_PASSWORD=carthographie
    D:DJANGO_SESSION_ENGINE=django.contrib.sessions.backends.db
    D:AUTH_MODE=mock
    D:USER_SCHEMA=users
    D:USER_TABLE=users
    D:DB_TEST_TEMPLATE=lss_local_template
