from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_animation", "0004_backgroundimage_storage_filename"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "common"."targets" (
                target_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name varchar(255) NOT NULL UNIQUE,
                sort_order integer NOT NULL
            );
            CREATE INDEX IF NOT EXISTS common_targets_sort_order_idx
                ON "common"."targets" (sort_order, target_id);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS "common"."common_targets_sort_order_idx";
            DROP TABLE IF EXISTS "common"."targets";
            """,
        ),
    ]
