# Generated by Django 6.0.3 on 2026-03-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE SCHEMA IF NOT EXISTS "lss";
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='SiteParams',
            fields=[
                ('language', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('title_h1', models.CharField(max_length=255)),
                ('home_text', models.TextField()),
                ('bloc1_text', models.TextField()),
                ('bloc2_text', models.TextField()),
                ('verse_max_lines', models.IntegerField()),
                ('verse_max_characters_for_a_line', models.IntegerField()),
                ('chorus_prefix', models.CharField(max_length=10)),
                ('verse_prefix1', models.CharField(max_length=10)),
                ('verse_prefix2', models.CharField(max_length=3)),
                ('admin_message', models.TextField()),
                ('moderator_message', models.TextField()),
                ('bg_img_max_bytes', models.IntegerField(default=2097152)),
                ('bg_img_min_w', models.IntegerField(default=800)),
                ('bg_img_min_h', models.IntegerField(default=600)),
                ('bg_img_max_w', models.IntegerField(default=4096)),
                ('bg_img_max_h', models.IntegerField(default=3072)),
                ('bg_img_ratio_min', models.DecimalField(decimal_places=1, default=1.3, max_digits=3)),
                ('bg_img_ratio_max', models.DecimalField(decimal_places=1, default=2.0, max_digits=3)),
                ('bg_img_allowed_ext', models.CharField(default='.jpg,.jpeg,.png', max_length=100)),
                ('bg_img_allowed_mime', models.CharField(default='image/jpeg,image/png', max_length=100)),
            ],
            options={
                'db_table': 'lss"."site_params',
            },
        ),
    ]
