name: PR Source Guard

on:
  pull_request:
    branches: [ main ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR head is "dev"
        run: |
          # Fails the job if the PR source branch isn't exactly "dev"
          echo "PR base: ${{ github.event.pull_request.base.ref }}"
          echo "PR head: ${{ github.event.pull_request.head.ref }}"
          if [ "${{ github.event.pull_request.base.ref }}" != "main" ]; then
            echo "This guard only applies to PRs targeting main."; exit 1
          fi
          if [ "${{ github.event.pull_request.head.ref }}" != "dev" ]; then
            echo "Only PRs from 'dev' to 'main' are allowed."; exit 1
          fi
